# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7519487194910a095c1b95666d9d4fb08ef4a4ff94d2d14ba075a1766afacbd6982dc172059f59e83eb7651cc848e62449fdb78b1ca93b8276ea879ec97e461

test:
  secret_key_base: 98e65288ce80eef6b9d73ed24b47a0fafd70382149ce4e2f06f5aba2745d48c70a90510ba5df48d4cdaf88aca73e56c8694232964ccfb8392b4702f492f36232

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
